In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df_2022 = pd.read_csv("./data/tmdb_2022.csv")

In [3]:
df_2022.head()

,title,release_date,type,runtime,season_count,episode_count,genre,director,cast,country,language,production_company,synopsis,tags,imdb_rating,imdb_review_count
0,My Massive Cock,2022-10-24,movie,47.0,NaN,NaN,Documentary,Mike Nicholls,"Matt Barr, Julia Davis",GB,en,"Channel 4 Television, Out of the Blue Productions",An extra-large penis is an object of desire fo...,"sexual problems, physical challenge, adult",5.800,8
1,365 Days: This Day,2022-04-26,movie,111.0,NaN,NaN,"Romance, Drama","Barbara Białowąs, Tomasz Mandes","Anna-Maria Sieklucka, Michele Morrone, Simone ...",PL,pl,"Ekipa, Open Mind Production",Laura and Massimo are back and hotter than eve...,"gangster, sequel, bdsm, rich man poor woman, s...",5.903,1726
2,Top Gun: Maverick,2022-05-21,movie,131.0,NaN,NaN,"Action, Drama",Joseph Kosinski,"Tom Cruise, Val Kilmer, Miles Teller, Jennifer...",US,en,"Skydance Media, Don Simpson/Jerry Bruckheimer ...",After more than thirty years of service as one...,"fighter pilot, u.s. navy, sequel, nuclear weap...",8.175,9921
3,Puss in Boots: The Last Wish,2022-12-07,movie,103.0,NaN,NaN,"Animation, Adventure, Fantasy, Comedy, Family",Joel Crawford,"Antonio Banderas, Salma Hayek Pinault, Harvey ...",US,en,DreamWorks Animation,Puss in Boots discovers that his passion for a...,"fairy tale, sequel, talking dog, spin off, aft...",8.216,8242
4,Avatar: The Way of Water,2022-12-14,movie,192.0,NaN,NaN,"Science Fiction, Adventure, Action",James Cameron,"Sam Worthington, Zoe Saldaña, Sigourney Weaver...",US,en,"20th Century Studios, Lightstorm Entertainment",Set more than a decade after the events of the...,"dying and death, loss of loved one, alien life...",7.611,12614

In [4]:
df_2022.isnull().sum()

title                     0
release_date              0
type                      0
runtime                6328
season_count          10000
episode_count         10000
genre                  2862
director               7682
cast                   3801
country                  27
language                  0
production_company     7564
synopsis               4463
tags                  15761
imdb_rating               0
imdb_review_count         0
dtype: int64

In [6]:
df_2022.shape

(20000, 16)

In [8]:
df_2022.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   title               20000 non-null  object
 1   release_date        20000 non-null  object
 2   type                20000 non-null  object
 3   runtime             13672 non-null  float64
 4   season_count        10000 non-null  float64
 5   episode_count       10000 non-null  float64
 6   genre               17138 non-null  object
 7   director            12318 non-null  object
 8   cast                16199 non-null  object
 9   country             19973 non-null  object
 10  language            20000 non-null  object
 11  production_company  12436 non-null  object
 12  synopsis            15537 non-null  object
 13  tags                4239 non-null   object
 14  imdb_rating         20000 non-null  float64
 15  imdb_review_count   20000 non-null  int64
dtypes: float64(4), int64(1), object(11)
memory usage: 2.4+ MB

In [9]:
df_2022.describe()

,runtime,season_count,episode_count,imdb_rating,imdb_review_count
count,13672.000000,10000.00000,10000.000000,20000.000000,20000.000000
mean,70.221621,1.33430,17.008300,3.757108,37.074200
std,44.380885,1.09739,37.094377,3.421635,308.465628
min,1.000000,1.00000,0.000000,0.000000,0.000000
25%,38.000000,1.00000,4.000000,0.000000,0.000000
50%,75.000000,1.00000,8.000000,4.600000,1.000000
75%,97.000000,1.00000,16.000000,6.800000,6.000000
max,780.000000,41.00000,774.000000,10.000000,12614.000000

## runtime 결측치 처리

In [10]:
median_runtime = df_2022['runtime'].median()
df_2022['runtime'] = df_2022['runtime'].fillna(median_runtime)

## episode, season count 결측치 처리

In [11]:
df_2022[df_2022['season_count'].isna() & df_2022['episode_count'].isna()].head(5)

,title,release_date,type,runtime,season_count,episode_count,genre,director,cast,country,language,production_company,synopsis,tags,imdb_rating,imdb_review_count
0,My Massive Cock,2022-10-24,movie,47.0,NaN,NaN,Documentary,Mike Nicholls,"Matt Barr, Julia Davis",GB,en,"Channel 4 Television, Out of the Blue Productions",An extra-large penis is an object of desire fo...,"sexual problems, physical challenge, adult",5.800,8
1,365 Days: This Day,2022-04-26,movie,111.0,NaN,NaN,"Romance, Drama","Barbara Białowąs, Tomasz Mandes","Anna-Maria Sieklucka, Michele Morrone, Simone ...",PL,pl,"Ekipa, Open Mind Production",Laura and Massimo are back and hotter than eve...,"gangster, sequel, bdsm, rich man poor woman, s...",5.903,1726
2,Top Gun: Maverick,2022-05-21,movie,131.0,NaN,NaN,"Action, Drama",Joseph Kosinski,"Tom Cruise, Val Kilmer, Miles Teller, Jennifer...",US,en,"Skydance Media, Don Simpson/Jerry Bruckheimer ...",After more than thirty years of service as one...,"fighter pilot, u.s. navy, sequel, nuclear weap...",8.175,9921
3,Puss in Boots: The Last Wish,2022-12-07,movie,103.0,NaN,NaN,"Animation, Adventure, Fantasy, Comedy, Family",Joel Crawford,"Antonio Banderas, Salma Hayek Pinault, Harvey ...",US,en,DreamWorks Animation,Puss in Boots discovers that his passion for a...,"fairy tale, sequel, talking dog, spin off, aft...",8.216,8242
4,Avatar: The Way of Water,2022-12-14,movie,192.0,NaN,NaN,"Science Fiction, Adventure, Action",James Cameron,"Sam Worthington, Zoe Saldaña, Sigourney Weaver...",US,en,"20th Century Studios, Lightstorm Entertainment",Set more than a decade after the events of the...,"dying and death, loss of loved one, alien life...",7.611,12614

In [12]:
df_2022[df_2022['season_count'].isna() & df_2022['episode_count'].isna()].shape

(10000, 16)

In [13]:
df_2022['type'].value_counts(dropna=False)

type
movie    10000
tv       10000
Name: count, dtype: int64

In [14]:
print(df_2022[df_2022['type'] == 'movie']['season_count'].value_counts(dropna=False))
print(df_2022[df_2022['type'] == 'movie']['episode_count'].value_counts(dropna=False))
# type이 movie인조건에서 season count, episode count Nan수

season_count
NaN    10000
Name: count, dtype: int64
episode_count
NaN    10000
Name: count, dtype: int64

In [15]:
df_2022_1 = df_2022

In [17]:
# movie인 경우 season/episode count가 NaN이면 1로 채움
df_2022_1.loc[df_2022_1['type'] == 'movie', ['season_count', 'episode_count']] = df_2022_1.loc[df_2022_1['type'] == 'movie', ['season_count', 'episode_count']].fillna(1)
pd.set_option('display.max_columns', None)
df_2022_1.head()

,title,release_date,type,runtime,season_count,episode_count,genre,director,cast,country,language,production_company,synopsis,tags,imdb_rating,imdb_review_count
0,My Massive Cock,2022-10-24,movie,47.0,1.0,1.0,Documentary,Mike Nicholls,"Matt Barr, Julia Davis",GB,en,"Channel 4 Television, Out of the Blue Productions",An extra-large penis is an object of desire fo...,"sexual problems, physical challenge, adult",5.800,8
1,365 Days: This Day,2022-04-26,movie,111.0,1.0,1.0,"Romance, Drama","Barbara Białowąs, Tomasz Mandes","Anna-Maria Sieklucka, Michele Morrone, Simone ...",PL,pl,"Ekipa, Open Mind Production",Laura and Massimo are back and hotter than eve...,"gangster, sequel, bdsm, rich man poor woman, s...",5.903,1726
2,Top Gun: Maverick,2022-05-21,movie,131.0,1.0,1.0,"Action, Drama",Joseph Kosinski,"Tom Cruise, Val Kilmer, Miles Teller, Jennifer...",US,en,"Skydance Media, Don Simpson/Jerry Bruckheimer ...",After more than thirty years of service as one...,"fighter pilot, u.s. navy, sequel, nuclear weap...",8.175,9921
3,Puss in Boots: The Last Wish,2022-12-07,movie,103.0,1.0,1.0,"Animation, Adventure, Fantasy, Comedy, Family",Joel Crawford,"Antonio Banderas, Salma Hayek Pinault, Harvey ...",US,en,DreamWorks Animation,Puss in Boots discovers that his passion for a...,"fairy tale, sequel, talking dog, spin off, aft...",8.216,8242
4,Avatar: The Way of Water,2022-12-14,movie,192.0,1.0,1.0,"Science Fiction, Adventure, Action",James Cameron,"Sam Worthington, Zoe Saldaña, Sigourney Weaver...",US,en,"20th Century Studios, Lightstorm Entertainment",Set more than a decade after the events of the...,"dying and death, loss of loved one, alien life...",7.611,12614

In [18]:
print(df_2022_1[df_2022_1['season_count'] == 1.0]['episode_count'].value_counts(dropna=False))

episode_count
1.0      11252
6.0        926
8.0        801
4.0        641
10.0       558
         ...
104.0        1
178.0        1
504.0        1
101.0        1
0.0          1
Name: count, Length: 163, dtype: int64

In [19]:
print(df_2022_1[df_2022_1['episode_count'] == 1.0]['season_count'].value_counts(dropna=False))

season_count
1.0     11252
2.0        29
3.0        11
4.0         4
9.0         1
15.0        1
21.0        1
6.0         1
12.0        1
41.0        1
Name: count, dtype: int64

In [23]:
df_2022_2 = df_2022_1
df_2022_2.loc[df_2022_2['type'] == 'tv', ['season_count', 'episode_count']] = df_2022_2.loc[df_2022_1['type'] == 'tv', ['season_count', 'episode_count']].fillna(1)
pd.set_option('display.max_columns', None)
df_2022_2.head()

,title,release_date,type,runtime,season_count,episode_count,genre,director,cast,country,language,production_company,synopsis,tags,imdb_rating,imdb_review_count
0,My Massive Cock,2022-10-24,movie,47.0,1.0,1.0,Documentary,Mike Nicholls,"Matt Barr, Julia Davis",GB,en,"Channel 4 Television, Out of the Blue Productions",An extra-large penis is an object of desire fo...,"sexual problems, physical challenge, adult",5.800,8
1,365 Days: This Day,2022-04-26,movie,111.0,1.0,1.0,"Romance, Drama","Barbara Białowąs, Tomasz Mandes","Anna-Maria Sieklucka, Michele Morrone, Simone ...",PL,pl,"Ekipa, Open Mind Production",Laura and Massimo are back and hotter than eve...,"gangster, sequel, bdsm, rich man poor woman, s...",5.903,1726
2,Top Gun: Maverick,2022-05-21,movie,131.0,1.0,1.0,"Action, Drama",Joseph Kosinski,"Tom Cruise, Val Kilmer, Miles Teller, Jennifer...",US,en,"Skydance Media, Don Simpson/Jerry Bruckheimer ...",After more than thirty years of service as one...,"fighter pilot, u.s. navy, sequel, nuclear weap...",8.175,9921
3,Puss in Boots: The Last Wish,2022-12-07,movie,103.0,1.0,1.0,"Animation, Adventure, Fantasy, Comedy, Family",Joel Crawford,"Antonio Banderas, Salma Hayek Pinault, Harvey ...",US,en,DreamWorks Animation,Puss in Boots discovers that his passion for a...,"fairy tale, sequel, talking dog, spin off, aft...",8.216,8242
4,Avatar: The Way of Water,2022-12-14,movie,192.0,1.0,1.0,"Science Fiction, Adventure, Action",James Cameron,"Sam Worthington, Zoe Saldaña, Sigourney Weaver...",US,en,"20th Century Studios, Lightstorm Entertainment",Set more than a decade after the events of the...,"dying and death, loss of loved one, alien life...",7.611,12614

## Genres 결측치 처리

In [24]:
df_2022_2['genre'] = df_2022_2['genre'].fillna('Unknown')
df_2022_2['genre_list'] = df_2022_2['genre'].apply(lambda x: [g.strip() for g in x.split(',')] if x else [])

In [25]:
df_2022_2.head()

,title,release_date,type,runtime,season_count,episode_count,genre,director,cast,country,language,production_company,synopsis,tags,imdb_rating,imdb_review_count,genre_list
0,My Massive Cock,2022-10-24,movie,47.0,1.0,1.0,Documentary,Mike Nicholls,"Matt Barr, Julia Davis",GB,en,"Channel 4 Television, Out of the Blue Productions",An extra-large penis is an object of desire fo...,"sexual problems, physical challenge, adult",5.800,8,[Documentary]
1,365 Days: This Day,2022-04-26,movie,111.0,1.0,1.0,"Romance, Drama","Barbara Białowąs, Tomasz Mandes","Anna-Maria Sieklucka, Michele Morrone, Simone ...",PL,pl,"Ekipa, Open Mind Production",Laura and Massimo are back and hotter than eve...,"gangster, sequel, bdsm, rich man poor woman, s...",5.903,1726,"[Romance, Drama]"
2,Top Gun: Maverick,2022-05-21,movie,131.0,1.0,1.0,"Action, Drama",Joseph Kosinski,"Tom Cruise, Val Kilmer, Miles Teller, Jennifer...",US,en,"Skydance Media, Don Simpson/Jerry Bruckheimer ...",After more than thirty years of service as one...,"fighter pilot, u.s. navy, sequel, nuclear weap...",8.175,9921,"[Action, Drama]"
3,Puss in Boots: The Last Wish,2022-12-07,movie,103.0,1.0,1.0,"Animation, Adventure, Fantasy, Comedy, Family",Joel Crawford,"Antonio Banderas, Salma Hayek Pinault, Harvey ...",US,en,DreamWorks Animation,Puss in Boots discovers that his passion for a...,"fairy tale, sequel, talking dog, spin off, aft...",8.216,8242,"[Animation, Adventure, Fantasy, Comedy, Family]"
4,Avatar: The Way of Water,2022-12-14,movie,192.0,1.0,1.0,"Science Fiction, Adventure, Action",James Cameron,"Sam Worthington, Zoe Saldaña, Sigourney Weaver...",US,en,"20th Century Studios, Lightstorm Entertainment",Set more than a decade after the events of the...,"dying and death, loss of loved one, alien life...",7.611,12614,"[Science Fiction, Adventure, Action]"

In [26]:
from itertools import chain

# 모든 영화의 genre_list를 합쳐서 유일 장르 set 생성
all_genres = set(chain.from_iterable(df_2022_2['genre_list']))
print(all_genres)

{'Soap', 'Drama', 'Romance', 'Unknown', 'Family', 'Animation', 'Documentary', 'Fantasy', 'War & Politics', 'Adventure', 'Thriller', 'Action & Adventure', 'Reality', 'Talk', 'Western', 'Sci-Fi & Fantasy', 'War', 'TV Movie', 'Horror', 'History', 'Comedy', 'Science Fiction', 'Music', 'Mystery', 'News', 'Action', 'Kids', 'Crime'}

In [29]:
# 각 유일 장르에 대해 원핫 컬럼 생성
for genre in all_genres:
    # genre가 해당 영화의 genre_list에 있으면 1, 아니면 0
    df_2022_2[f'genre_{genre}'] = df_2022_2['genre_list'].apply(lambda x: int(genre in x))

In [30]:
df_2022_2.columns

Index(['title', 'release_date', 'type', 'runtime', 'season_count',
       'episode_count', 'genre', 'director', 'cast', 'country', 'language',
       'production_company', 'synopsis', 'tags', 'imdb_rating',
       'imdb_review_count', 'genre_list', 'genre_Soap', 'genre_Drama',
       'genre_Romance', 'genre_Unknown', 'genre_Family', 'genre_Animation',
       'genre_Documentary', 'genre_Fantasy', 'genre_War & Politics',
       'genre_Adventure', 'genre_Thriller', 'genre_Action & Adventure',
       'genre_Reality', 'genre_Talk', 'genre_Western',
       'genre_Sci-Fi & Fantasy', 'genre_War', 'genre_TV Movie', 'genre_Horror',
       'genre_History', 'genre_Comedy', 'genre_Science Fiction', 'genre_Music',
       'genre_Mystery', 'genre_News', 'genre_Action', 'genre_Kids',
       'genre_Crime'],
      dtype='object')

## director 결측치처리

In [31]:
df_2022_2['director'] = df_2022_2['director'].fillna('Unknown')

## cast 결측치 처리

In [32]:
df_2022_2['cast'] = df_2022_2['cast'].fillna('Unknown')

## country 결측치 처리

In [33]:
df_2022_2['country'] = df_2022_2['country'].fillna('Unknown')

## production company 결측치 처리

In [34]:
df_2022_2['production_company'] = df_2022_2['production_company'].fillna('Unknown')

## synopsis 결측치 처리

In [37]:
if 'synopsis' in df_2022_2.columns:
    df_2022_2.drop(columns=['synopsis'], inplace=True)

In [38]:
df_2022_2.columns

Index(['title', 'release_date', 'type', 'runtime', 'season_count',
       'episode_count', 'genre', 'director', 'cast', 'country', 'language',
       'production_company', 'tags', 'imdb_rating', 'imdb_review_count',
       'genre_list', 'genre_Soap', 'genre_Drama', 'genre_Romance',
       'genre_Unknown', 'genre_Family', 'genre_Animation', 'genre_Documentary',
       'genre_Fantasy', 'genre_War & Politics', 'genre_Adventure',
       'genre_Thriller', 'genre_Action & Adventure', 'genre_Reality',
       'genre_Talk', 'genre_Western', 'genre_Sci-Fi & Fantasy', 'genre_War',
       'genre_TV Movie', 'genre_Horror', 'genre_History', 'genre_Comedy',
       'genre_Science Fiction', 'genre_Music', 'genre_Mystery', 'genre_News',
       'genre_Action', 'genre_Kids', 'genre_Crime'],
      dtype='object')

## tags 결측치  처리

In [39]:
from sklearn.feature_extraction.text import TfidfVectorizer

# 2️⃣ tags 컬럼 결측치 확인 및 제거
df_2022_2_tags = df_2022_2.dropna(subset=['tags']).copy()

# 3️⃣ tags 문자열 전처리: 콤마(,) → 공백으로 변환하여 TF-IDF가 단어 구분 가능하도록 함
df_2022_2_tags['tags_text'] = df_2022_2_tags['tags'].apply(lambda x: x.replace(',', ' '))

# 4️⃣ TF-IDF 벡터라이저 생성
# (상위 50개의 가장 많이 등장하는 단어만 feature로 추출)
vectorizer = TfidfVectorizer(max_features=50)

# 5️⃣ TF-IDF 벡터화 적용
tfidf_matrix = vectorizer.fit_transform(df_2022_2_tags['tags_text'])

# 6️⃣ 벡터 결과를 데이터프레임으로 변환 (컬럼명: 추출된 단어 리스트)
tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), columns=vectorizer.get_feature_names_out())

# 7️⃣ 원본 데이터와 TF-IDF 결과 병합
df_2022_2_with_tfidf = pd.concat([df_2022_2_tags.reset_index(drop=True), tfidf_df], axis=1)

# 8️⃣ 결과 일부 확인
print(df_2022_2_with_tfidf.head())

                          title release_date   type  runtime  season_count  \
0               My Massive Cock   2022-10-24  movie     47.0           1.0
1            365 Days: This Day   2022-04-26  movie    111.0           1.0
2             Top Gun: Maverick   2022-05-21  movie    131.0           1.0
3  Puss in Boots: The Last Wish   2022-12-07  movie    103.0           1.0
4      Avatar: The Way of Water   2022-12-14  movie    192.0           1.0

   episode_count                                          genre  \
0            1.0                                    Documentary
1            1.0                                 Romance, Drama
2            1.0                                  Action, Drama
3            1.0  Animation, Adventure, Fantasy, Comedy, Family
4            1.0             Science Fiction, Adventure, Action

                          director  \
0                    Mike Nicholls
1  Barbara Białowąs, Tomasz Mandes
2                  Joseph Kosinski
3                    Joel Crawford
4                    James Cameron

                                                cast country language  \
0                             Matt Barr, Julia Davis      GB       en
1  Anna-Maria Sieklucka, Michele Morrone, Simone ...      PL       pl
2  Tom Cruise, Val Kilmer, Miles Teller, Jennifer...      US       en
3  Antonio Banderas, Salma Hayek Pinault, Harvey ...      US       en
4  Sam Worthington, Zoe Saldaña, Sigourney Weaver...      US       en

                                  production_company  \
0  Channel 4 Television, Out of the Blue Productions
1                        Ekipa, Open Mind Production
2  Skydance Media, Don Simpson/Jerry Bruckheimer ...
3                               DreamWorks Animation
4     20th Century Studios, Lightstorm Entertainment

                                                tags  imdb_rating  \
0         sexual problems, physical challenge, adult        5.800
1  gangster, sequel, bdsm, rich man poor woman, s...        5.903
2  fighter pilot, u.s. navy, sequel, nuclear weap...        8.175
3  fairy tale, sequel, talking dog, spin off, aft...        8.216
4  dying and death, loss of loved one, alien life...        7.611

   imdb_review_count                                       genre_list  \
0                  8                                    [Documentary]
1               1726                                 [Romance, Drama]
2               9921                                  [Action, Drama]
3               8242  [Animation, Adventure, Fantasy, Comedy, Family]
4              12614             [Science Fiction, Adventure, Action]

   genre_Soap  genre_Drama  genre_Romance  genre_Unknown  genre_Family  \
0           0            0              0              0             0
1           0            1              1              0             0
2           0            1              0              0             0
3           0            0              0              0             1
4           0            0              0              0             0

   genre_Animation  genre_Documentary  genre_Fantasy  genre_War & Politics  \
0                0                  1              0                     0
1                0                  0              0                     0
2                0                  0              0                     0
3                1                  0              1                     0
4                0                  0              0                     0

   genre_Adventure  genre_Thriller  genre_Action & Adventure  genre_Reality  \
0                0               0                         0              0
1                0               0                         0              0
2                0               0                         0              0
3                1               0                         0              0
4                1               0                         0              0

   genre_Talk  genre_Western  genre_Sci-Fi & Fantasy  genre_War  \
0           0              0                       0          0
1           0              0                       0          0
2           0              0                       0          0
3           0              0                       0          0
4           0              0                       0          0

   genre_TV Movie  genre_Horror  genre_History  genre_Comedy  \
0               0             0              0             0
1               0             0              0             0
2               0             0              0             0
3               0             0              0             1
4               0             0              0             0

   genre_Science Fiction  genre_Music  genre_Mystery  genre_News  \
0                      0            0              0           0
1                      0            0              0           0
2                      0            0              0           0
3                      0            0              0           0
4                      1            0              0           0

   genre_Action  genre_Kids  genre_Crime  \
0             0           0            0
1             0           0            0
2             1           0            0
3             0           0            0
4             1           0            0

                                           tags_text  age       and  based  \
0         sexual problems  physical challenge  adult  0.0  0.000000    0.0
1  gangster  sequel  bdsm  rich man poor woman  s...  0.0  0.000000    0.0
2  fighter pilot  u.s. navy  sequel  nuclear weap...  0.0  0.000000    0.0
3  fairy tale  sequel  talking dog  spin off  aft...  0.0  0.000000    0.0
4  dying and death  loss of loved one  alien life...  0.0  0.327124    0.0

   biography  book     child  christmas  cinema  comedy  coming  concert  \
0        0.0   0.0  0.000000        0.0     0.0     0.0     0.0      0.0
1        0.0   0.0  0.000000        0.0     0.0     0.0     0.0      0.0
2        0.0   0.0  0.000000        0.0     0.0     0.0     0.0      0.0
3        0.0   0.0  0.000000        0.0     0.0     0.0     0.0      0.0
4        0.0   0.0  0.354932        0.0     0.0     0.0     0.0      0.0

      death  director  documentary    family  father      film  footage  \
0  0.000000       0.0          0.0  0.000000     0.0  0.000000      0.0
1  0.000000       0.0          0.0  0.000000     0.0  0.000000      0.0
2  0.000000       0.0          0.0  0.000000     0.0  0.000000      0.0
3  0.809375       0.0          0.0  0.000000     0.0  0.000000      0.0
4  0.341553       0.0          0.0  0.573169     0.0  0.233706      0.0

   friendship  gay  history  horror   in  lgbt      life  love  mother  \
0         0.0  0.0      0.0     0.0  0.0   0.0  0.000000   0.0     0.0
1         0.0  0.0      0.0     0.0  0.0   0.0  0.000000   0.0     0.0
2         0.0  0.0      0.0     0.0  0.0   0.0  0.000000   0.0     0.0
3         0.0  0.0      0.0     0.0  0.0   0.0  0.000000   0.0     0.0
4         0.0  0.0      0.0     0.0  0.0   0.0  0.325284   0.0     0.0

   murder  music  new  novel        of   on   or  relationship  romance  \
0     0.0    0.0  0.0    0.0  0.000000  0.0  0.0           0.0      0.0
1     0.0    0.0  0.0    0.0  0.000000  0.0  0.0           0.0      0.0
2     0.0    0.0  0.0    0.0  0.000000  0.0  0.0           0.0      0.0
3     0.0    0.0  0.0    0.0  0.587292  0.0  0.0           0.0      0.0
4     0.0    0.0  0.0    0.0  0.247835  0.0  0.0           0.0      0.0

   school  short  social  sports  stand  story  superhero  the  theme  true  \
0     0.0    0.0     0.0     0.0    0.0    0.0        0.0  0.0    0.0   0.0
1     0.0    0.0     0.0     0.0    0.0    0.0        0.0  0.0    0.0   0.0
2     0.0    0.0     0.0     0.0    0.0    0.0        0.0  0.0    0.0   0.0
3     0.0    0.0     0.0     0.0    0.0    0.0        0.0  0.0    0.0   0.0
4     0.0    0.0     0.0     0.0    0.0    0.0        0.0  0.0    0.0   0.0

    up     war  woman  world
0  0.0  0.0000    0.0    0.0
1  0.0  0.0000    1.0    0.0
2  0.0  1.0000    0.0    0.0
3  0.0  0.0000    0.0    0.0
4  0.0  0.3162    0.0    0.0

In [41]:
df_2022_2_with_tfidf.head(10) # -> tags까지 nlp후에 2022년 데이터 결과

,title,release_date,type,runtime,season_count,episode_count,genre,director,cast,country,language,production_company,tags,imdb_rating,imdb_review_count,genre_list,genre_Soap,genre_Drama,genre_Romance,genre_Unknown,genre_Family,genre_Animation,genre_Documentary,genre_Fantasy,genre_War & Politics,genre_Adventure,genre_Thriller,genre_Action & Adventure,genre_Reality,genre_Talk,genre_Western,genre_Sci-Fi & Fantasy,genre_War,genre_TV Movie,genre_Horror,genre_History,genre_Comedy,genre_Science Fiction,genre_Music,genre_Mystery,genre_News,genre_Action,genre_Kids,genre_Crime,tags_text,age,and,based,biography,book,child,christmas,cinema,comedy,coming,concert,death,director,documentary,family,father,film,footage,friendship,gay,history,horror,in,lgbt,life,love,mother,murder,music,new,novel,of,on,or,relationship,romance,school,short,social,sports,stand,story,superhero,the,theme,true,up,war,woman,world
0,My Massive Cock,2022-10-24,movie,47.0,1.0,1.0,Documentary,Mike Nicholls,"Matt Barr, Julia Davis",GB,en,"Channel 4 Television, Out of the Blue Productions","sexual problems, physical challenge, adult",5.800,8,[Documentary],0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,sexual problems physical challenge adult,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0000,0.0,0.0
1,365 Days: This Day,2022-04-26,movie,111.0,1.0,1.0,"Romance, Drama","Barbara Białowąs, Tomasz Mandes","Anna-Maria Sieklucka, Michele Morrone, Simone ...",PL,pl,"Ekipa, Open Mind Production","gangster, sequel, bdsm, rich man poor woman, s...",5.903,1726,"[Romance, Drama]",0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,gangster sequel bdsm rich man poor woman s...,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0000,1.0,0.0
2,Top Gun: Maverick,2022-05-21,movie,131.0,1.0,1.0,"Action, Drama",Joseph Kosinski,"Tom Cruise, Val Kilmer, Miles Teller, Jennifer...",US,en,"Skydance Media, Don Simpson/Jerry Bruckheimer ...","fighter pilot, u.s. navy, sequel, nuclear weap...",8.175,9921,"[Action, Drama]",0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,fighter pilot u.s. navy sequel nuclear weap...,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,1.0000,0.0,0.0
3,Puss in Boots: The Last Wish,2022-12-07,movie,103.0,1.0,1.0,"Animation, Adventure, Fantasy, Comedy, Family",Joel Crawford,"Antonio Banderas, Salma Hayek Pinault, Harvey ...",US,en,DreamWorks Animation,"fairy tale, sequel, talking dog, spin off, aft...",8.216,8242,"[Animation, Adventure, Fantasy, Comedy, Family]",0,0,0,0,1,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,fairy tale sequel talking dog spin off aft...,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.809375,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.587292,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0000,0.0,0.0
4,Avatar: The Way of Water,2022-12-14,movie,192.0,1.0,1.0,"Science Fiction, Adventure, Action",James Cameron,"Sam Worthington, Zoe Saldaña, Sigourney Weaver...",US,en,"20th Century Studios, Lightstorm Entertainment","dying and death, loss of loved one, alien life...",7.611,12614,"[Science Fiction, Adventure, Action]",0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,dying and death loss of loved one alien life...,0.0,0.327124,0.000000,0.0,0.0,0.354932,0.0,0.0,0.0,0.0,0.0,0.341553,0.0,0.0,0.573169,0.0,0.233706,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.325284,0.0,0.0,0.000000,0.0,0.0,0.0,0.247835,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.3162,0.0,0.0
5,Jurassic World Dominion,2022-06-01,movie,147.0,1.0,1.0,"Adventure, Action, Science Fiction",Colin Trevorrow,"Chris Pratt, Bryce Dallas Howard, Laura Dern, ...",US,en,"Amblin Entertainment, Universal Pictures","paleontology, giant monster, sequel, survival,...",6.700,6410,"[Adventure, Action, Science Fiction]",0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,paleontology giant monster sequel survival ...,0.0,0.000000,0.000000,0.0,0.0,1.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0000,0.0,0.0
6,The Batman,2022-03-01,movie,177.0,1.0,1.0,"Crime, Mystery, Thriller",Matt Reeves,"Robert Pattinson, Zoë Kravitz, Jeffrey Wright,...",US,en,"6th & Idaho Motion Picture Company, Dylan Clar...","police, psychopath, secret identity, crime fig...",7.700,10966,"[Crime, Mystery, Thriller]",0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,police psychopath secret identity crime fig...,0.0,0.000000,0.252807,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.360931,0.0,0.0,0.0,0.000000,0.246989,0.0,0.0,0.0,0.0,0.0,0.349134,0.0,0.0,0.0,0.789252,0.0,0.0,0.0,0.0,0.0000,0.0,0.0
7,Prey,2022-08-02,movie,100.0,1.0,1.0,"Thriller, Action, Science Fiction",Dan Trachtenberg,"Amber Midthunder, Dakota Beavers, Michelle Thr...",US,en,"20th Century Studios, Davis Entertainment, Law...","hunter, native american, alien life-form, alie...",7.690,7057,"[Thriller, Action, Science Fiction]",0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,hunter native american alien life-form alie...,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0000,0.0,0.0
8,Sonic the Hedgehog 2,2022-03-30,movie,123.0,1.0,1.0,"Action, Adventure, Family, Comedy",Jeff Fowler,"Ben Schwartz, James Marsden, Tika Sumpter, Col...",US,en,"Original Film, Blur Studio, Marza Animation Pl...","mad scientist, sequel, revenge, based on video...",7.465,5530,"[Action, Adventure, Family, Comedy]",0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,mad scientist sequel revenge based on video...,0.0,0.700020,0.510805,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.499049,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0000,0.0,0.0
9,Doctor Strange in the Multiverse of Madness,2022-05-04,movie,126.0,1.0,1.0,"Fantasy, Action, Adventure",Sam Raimi,"Benedict Cumberbatch, Xochitl Gomez, Elizabeth...",US,en,"Marvel Studios, Kevin Feige Productions","magic, superhero, based on comic, alternative ...",7.259,9584,"[Fantasy, Action, Adventure]",0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,magic superhero based on comic alternative ...,0.0,0.000000,0.477211,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.466228,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.744916,0.0,0.0,0.0,0.0,0.0000,0.0,0.0

In [42]:
df_2022_2_with_tfidf['tags'].isnull().sum()

0

In [44]:
df_2022_2_with_tfidf.shape

(4239, 95)